name: NMinimap
version: '1.0.9'
main: su.nezushin.nminimap.NMinimap
api-version: '1.21'

authors:
  - NezuShin
  - DartCat25

commands:
  minimap:
    aliases: [mm]

softdepend:
  - packetevents
  - PassengerAPI
  - AnvilORM
  - PlaceholderAPI
  - WorldGuard
  - Geyser-Spigot



folia-supported: true

permissions:
  nminimap.admin:
    description: Access to admin commands
  nminimap.command.minimap:
    description: Access to /minimap player commands when command-permission.use is enabled; also required to keep the minimap on when command-permission.apply-to-minimap is enabled
  nminimap.hide-on-map:
    description: Hide this player from other players' minimaps when hide-permission is enabled
  nminimap.scale.1:
    description: Allow using /mm scale 1 when scale.use-permission is enabled
  nminimap.scale.2:
    description: Allow using /mm scale 2 when scale.use-permission is enabled
  nminimap.scale.4:
    description: Allow using /mm scale 4 when scale.use-permission is enabled
  nminimap.scale.8:
    description: Allow using /mm scale 8 when scale.use-permission is enabled
  nminimap.frame.default:
    description: Allow using /mm frame default when frames.default.use-permission is enabled
  nminimap.frame.inventory_with_title:
    description: Allow using /mm frame inventory_with_title when frames.inventory_with_title.use-permission is enabled
  nminimap.allow-radar:
    description: Allow using /mm radar enable when markers.mob-radar.use-permission is enabled
  nminimap.bedrock-bypass:
    description: Allow Bedrock players to use the minimap despite Bedrock restrictions


libraries:
  - net.kyori:adventure-text-minimessage:4.23.0
  - net.kyori:adventure-text-serializer-gson:4.23.0
  - net.kyori:adventure-text-serializer-legacy:4.23.0
  - de.clickism:modrinth-update-checker:1.0
